### ISSUE TITLE
loading demos for cp_process versions other than _final defaults to previously displayed map mesh instead of process map mesh

### ISSUE THREAD

**Issue by ambroshia** [bryjch/dribble.tf#3]
When loading a demo for cp_process versions other than the final version, such as cp_process_f7, or cp_process_f5, the map mesh will not be changed to cp_process' map mesh.

Instead, the demo will have the map mesh of whichever map that was present in the previously loaded demo.

![product_mesh_on_process_f7](https://user-images.githubusercontent.com/56530123/122386806-c4776800-cf5d-11eb-8a19-36f4c3803bf3.JPG)
Since the site defaults to the product map mesh when it is first opened, loading a cp_process_f7 demo will display the players on the product map mesh.

![snakewater_mesh_on_process_f5](https://user-images.githubusercontent.com/56530123/122386818-c7725880-cf5d-11eb-9e6b-dc8e7820525c.JPG)
After loading the sample demo on snakewater, then loading a cp_process_f5 demo, the map mesh will remain the snakewater map, and will not be updated to the process map mesh.

**Comment by bryjch** [comment]
Hey @ambroshia, thanks for the detailed info. I've pushed a fix to parse the loaded map name.

Although I will just be using the same default map models (`_final` versions) instead of generating new map models (I think most of the maps have relatively minor changes only?)

It should work for all other maps with different version naming too.

Let me know if it works!

**Comment by ambroshia** [comment]
Just tested loading both a cp_process_f7 and cp_process_f5 demo, each time the map mesh successfully changed to the process one. 

> Although I will just be using the same default map models (_final versions) instead of generating new map models (I think most of the maps have relatively minor changes only?)

Yeah, I've heard that there are only very minor differences for small props, it shouldn't have a noticeable difference.

Thank you for the fix.
